relase wf

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -57,11 +57,6 @@ jobs:
           echo "docker --version"; docker --version
           echo "docker-compose --version"; docker-compose --version
 
-      - name: TEST
-        run: |
-          echo "testing release"
-          exit 1
-
       - uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
@@ -70,16 +65,20 @@ jobs:
       - name: Release
         run: |
           export NODE_AUTH_TOKEN=${{ secrets.NPM_TOKEN }}
-          export APIM_SOLACE_PLATFORM_API_PROJECT_HOME="$GITHUB_WORKSPACE"
-          cd "$APIM_SOLACE_PLATFORM_API_PROJECT_HOME/${RELEASE_PLATFORM_DIR}"
+          cd "$GITHUB_WORKSPACE/${RELEASE_DIR}"
           ./release.sh
 
-      - name: Archive logs
-        if: ${{ (failure() && !cancelled()) || (always() && (github.event_name=='workflow_dispatch' || env.DEBUG_FLAG=='true') ) }}
-        uses: actions/upload-artifact@v2
-        with:
-          name: ${{ env.RELEASE_OUTPUT_NAME }}
-          path: ${{ github.workspace }}/${{ env.RELEASE_RUNNER_OUTPUT_DIR }}
-          if-no-files-found: error
+      - name: TEST
+        run: |
+          echo "testing release"
+          exit 1
+
+      # - name: Archive logs
+      #   if: ${{ (failure() && !cancelled()) || (always() && (github.event_name=='workflow_dispatch' || env.DEBUG_FLAG=='true') ) }}
+      #   uses: actions/upload-artifact@v2
+      #   with:
+      #     name: ${{ env.RELEASE_OUTPUT_NAME }}
+      #     path: ${{ github.workspace }}/${{ env.RELEASE_RUNNER_OUTPUT_DIR }}
+      #     if-no-files-found: error
 ###
 # The End.
